#' Fit a Bayesian regression model
#'
#' Fits a Bayesian regression model using Greta and generates posterior
#' samples and summary statistics for downstream analysis.
#'
#' @param x Predictor variables
#' @param y Response variable
#' @param n_samples Number of MCMC samples. Default is 1000
#' @param chains Number of MCMC chains. Default is 4
#'
#' @returns A list containing:
#' \itemize{
#'   \item \code{model}: The Greta model object.
#'   \item \code{fit}: Posterior samples generated by MCMC.
#'   \item \code{fit_summary}: Summary statistics and convergence diagnostics.
#' }
#'
#' @export
#'
#' @examples
#' fit_model <- fit_model(x=observation_list, y=iris$Sepal.Length)
fit_model <- function (x, y, n_samples=1000,chains=4) {
  
  # Convert to greta data object
  x_data <- as_data(as.matrix(data.frame(x)))
  y_data <- as_data(y)
  
  p <- ncol(as.matrix(data.frame(x)))
  
  # priors
  int <- normal(5.5, 0.5)
  coef <- normal(0.5, 0.2, dim = p)
  sd <- normal(0, 0.4, truncation = c(0, Inf))
  
  mean <- int + x_data %*% coef
  distribution(y_data) <- normal(mean,sd) 
  
  # Fit the model
  m <- model(int, coef, sd)

  # Fit the model and generate posterior samples
  fit <- mcmc(m, n_samples = n_samples, chains = chains)
  
  # Create a summary matrix used by diagnostic and visualisation functions
  fit_summary <- summarise_greta(fit)
  
  fit_output <- list(
    model=m,
    fit=fit,
    fit_summary=fit_summary
  )
  
  return(fit_output)
}



